import type { ExerciseItem } from './types';

export const EXERCISE_CATALOG: Record<string, ExerciseItem> = {
  push_up: {
    id: 'push_up',
    name: 'Push-up',
    category: 'dada',
    description: 'Latihan dasar kekuatan tubuh bagian atas untuk membentuk otot dada, trisep, dan bahu.',
    instructions: [
      'Posisikan tangan di lantai selebar bahu dan tubuh lurus dari kepala hingga tumit.',
      'Turunkan dada perlahan hingga siku membentuk sudut ~90 derajat.',
      'Dorong kembali ke posisi awal dengan mengencangkan otot dada dan perut.',
    ],
    targetMuscles: ['Dada', 'Trisep', 'Bahu Depan', 'Core'],
    defaultSets: 3,
    defaultReps: 10,
    caloriesPerMinute: 8.5,
    supportedAiCode: 'push_up',
    visualKey: 'push_up',
  },
  squat: {
    id: 'squat',
    name: 'Bodyweight Squat',
    category: 'kaki',
    description: 'Latihan utama tubuh bagian bawah untuk menguatkan paha depan, paha belakang, dan gluteus.',
    instructions: [
      'Berdiri tegak dengan kaki selebar bahu dan ujung jari sedikit menghadap keluar.',
      'Dorong pinggul ke belakang seolah hendak duduk di kursi, tekuk lutut hingga paha sejajar lantai.',
      'Pastikan dada tetap tegak dan lutut sejajar dengan arah jari kaki.',
      'Dorong melalui tumit untuk kembali berdiri tegak.',
    ],
    targetMuscles: ['Paha Depan (Quadriceps)', 'Gluteus', 'Paha Belakang (Hamstrings)'],
    defaultSets: 3,
    defaultReps: 12,
    caloriesPerMinute: 9.0,
    supportedAiCode: 'squat',
    visualKey: 'squat',
  },
  sit_up: {
    id: 'sit_up',
    name: 'Sit-up / Crunches',
    category: 'perut',
    description: 'Latihan pengencangan otot perut bagian tengah dan atas untuk membangun daya tahan core.',
    instructions: [
      'Berbaring di matras dengan lutut ditekuk dan telapak kaki menapak rata di lantai.',
      'Letakkan tangan di dekat telinga atau menyilang di dada, jangan menarik leher.',
      'Angkat tubuh bagian atas menggunakan kontraksi otot perut.',
      'Turunkan kembali secara terkontrol.',
    ],
    targetMuscles: ['Perut (Rectus Abdominis)', 'Otot Perut Samping (Obliques)'],
    defaultSets: 3,
    defaultReps: 12,
    caloriesPerMinute: 7.0,
    supportedAiCode: 'sit_up',
    visualKey: 'sit_up',
  },
  plank: {
    id: 'plank',
    name: 'Core Plank',
    category: 'core',
    description: 'Latihan isometrik terbaik untuk menguatkan seluruh sabuk otot perut dan menjaga kesehatan tulang belakang.',
    instructions: [
      'Posisikan lengan bawah di lantai sejajar dengan bahu.',
      'Luruskan kaki ke belakang dengan tumpuan pada ujung jari kaki.',
      'Kencangkan perut, bokong, dan paha agar tubuh membentuk garis lurus sempurna.',
      'Bernapas teratur dan tahan posisi tanpa membiarkan pinggul merosot.',
    ],
    targetMuscles: ['Core Dalam', 'Perut', 'Punggung Bawah', 'Bahu'],
    defaultSets: 3,
    defaultDurationSeconds: 30,
    caloriesPerMinute: 6.5,
    supportedAiCode: 'plank',
    visualKey: 'plank',
  },
  arm_raise: {
    id: 'arm_raise',
    name: 'Overhead Barbell / Arm Raise',
    category: 'bahu',
    description: 'Latihan mobilitas dan daya tahan otot bahu serta punggung atas dengan postur tegak.',
    instructions: [
      'Berdiri tegak dengan kaki selebar pinggul dan kedua lengan di samping.',
      'Angkat kedua tangan lurus ke atas kepala secara terkontrol.',
      'Rasakan kontraksi pada otot bahu saat lengan lurus di atas.',
      'Turunkan kembali ke posisi semula dengan tempo stabil.',
    ],
    targetMuscles: ['Bahu (Deltoids)', 'Trapezius', 'Punggung Atas'],
    defaultSets: 3,
    defaultReps: 15,
    caloriesPerMinute: 6.0,
    supportedAiCode: 'arm_raise',
    visualKey: 'arm_raise',
  },
  jumping_jacks: {
    id: 'jumping_jacks',
    name: 'Jumping Jacks',
    category: 'kardio',
    description: 'Gerakan kardio dinamis untuk membakar kalori cepat, menaikkan detak jantung, dan melatih koordinasi.',
    instructions: [
      'Mulai dengan berdiri tegak, kaki rapat, dan kedua tangan di samping paha.',
      'Lompat membuka kaki selebar bahu sambil mengangkat kedua tangan bertepuk di atas kepala.',
      'Lompat kembali ke posisi awal secara ritmis dan jaga pendaratan tetap empuk dengan ujung kaki.',
    ],
    targetMuscles: ['Jantung (Cardio)', 'Betis', 'Bahu', 'Paha'],
    defaultSets: 3,
    defaultDurationSeconds: 40,
    caloriesPerMinute: 11.0,
    visualKey: 'jumping_jacks',
  },
  high_knees: {
    id: 'high_knees',
    name: 'High Knees',
    category: 'kardio',
    description: 'Lari di tempat dengan lutut diangkat setinggi pinggul untuk mengikis lemak perut dan meningkatkan daya tahan aerobik.',
    instructions: [
      'Berdiri tegak, lalu lari di tempat dengan mengangkat lutut bergantian hingga setinggi pinggang.',
      'Ayunkan lengan berlawanan dengan irama kaki untuk menjaga momentum dan keseimbangan.',
      'Jaga tubuh tetap condong sedikit ke depan dan pendaratan ringan.',
    ],
    targetMuscles: ['Kardio', 'Fleksor Pinggul', 'Paha Depan', 'Perut Bawah'],
    defaultSets: 3,
    defaultDurationSeconds: 30,
    caloriesPerMinute: 12.0,
    visualKey: 'high_knees',
  },
  mountain_climbers: {
    id: 'mountain_climbers',
    name: 'Mountain Climbers',
    category: 'core',
    description: 'Kombinasi luar biasa antara penguatan core dan pembakaran kalori dalam posisi plank.',
    instructions: [
      'Mulai dari posisi push-up / high plank dengan tangan menopang tubuh di bawah bahu.',
      'Tarik satu lutut ke arah dada dengan cepat tanpa menaikkan pinggul terlalu tinggi.',
      'Ganti kaki secara dinamis dengan tempo stabil seperti sedang berlari mendaki.',
    ],
    targetMuscles: ['Core', 'Bahu', 'Perut', 'Paha'],
    defaultSets: 3,
    defaultDurationSeconds: 30,
    caloriesPerMinute: 10.5,
    visualKey: 'mountain_climbers',
  },
  lunges: {
    id: 'lunges',
    name: 'Forward Lunges',
    category: 'kaki',
    description: 'Latihan unilateral untuk membentuk paha, menguatkan bokong, dan meningkatkan stabilitas sendi lutut.',
    instructions: [
      'Langkahkan satu kaki ke depan dan turunkan pinggul hingga kedua lutut membentuk sudut ~90 derajat.',
      'Pastikan lutut depan tidak melebihi ujung jari kaki dan lutut belakang hampir menyentuh lantai.',
      'Dorong tumit depan untuk kembali berdiri dan ulangi untuk kaki berikutnya.',
    ],
    targetMuscles: ['Quadriceps', 'Gluteus', 'Hamstrings', 'Betis'],
    defaultSets: 3,
    defaultReps: 12,
    caloriesPerMinute: 8.0,
    visualKey: 'lunges',
  },
  cobra_stretch: {
    id: 'cobra_stretch',
    name: 'Cobra Stretch',
    category: 'fleksibilitas',
    description: 'Peregangan lembut untuk membuka dada, melancarkan sirkulasi, dan meredakan ketegangan punggung bawah.',
    instructions: [
      'Tengkurap di lantai dengan telapak tangan diletakkan di samping dada.',
      'Tekan telapak tangan perlahan untuk mengangkat dada ke atas, biarkan pinggul tetap menempel di lantai.',
      'Buka bahu ke belakang dan tarik napas dalam, tahan regangan tanpa memaksakan tulang belakang.',
    ],
    targetMuscles: ['Punggung Bawah', 'Dada', 'Perut', 'Fleksor Tulang Belakang'],
    defaultSets: 2,
    defaultDurationSeconds: 30,
    caloriesPerMinute: 3.5,
    visualKey: 'cobra_stretch',
  },
  child_pose: {
    id: 'child_pose',
    name: "Child's Pose",
    category: 'fleksibilitas',
    description: 'Pose pemulihan aktif yang menenangkan sistem saraf dan meregangkan punggung, bahu, serta pinggul.',
    instructions: [
      'Berlutut di lantai, duduk di atas tumit dengan jempol kaki bersentuhan.',
      'Rendahkan tubuh ke depan hingga dahi menyentuh lantai dan rentangkan kedua tangan lurus ke depan.',
      'Tarik napas perlahan dan biarkan seluruh tubuh rileks melepaskan sisa beban latihan.',
    ],
    targetMuscles: ['Punggung Seluruhnya', 'Bahu', 'Pinggul', 'Pelemasan Saraf'],
    defaultSets: 2,
    defaultDurationSeconds: 40,
    caloriesPerMinute: 3.0,
    visualKey: 'child_pose',
  },
};

export const EXERCISE_ARRAY = Object.values(EXERCISE_CATALOG);
